
dynamic api_dashboard_error_example = {
  "data": [
    {"count": 4, "error_code": "G0012", "percentage": 36.36},
    {"count": 4, "error_code": "G0014", "percentage": 36.36},
    {"count": 3, "error_code": "G0015", "percentage": 27.27},
  ],
};

dynamic getErrorDetail_example = {
  "data": [
    {
      "cause": "Xylanh không đi hết hành trình",
      "error_id": 27,
      "error_name": "Bất thường xylanh/Cylinder error",
      "solution": "Kiểm tra van, khí, đế van...",
      "used_count": 3,
    },
    {
      "cause": "Xylanh không đi hết hành trình",
      "error_id": 27,
      "error_name": "Bất thường xylanh/Cylinder error",
      "solution": "Kiểm tra cảm biến...",
      "used_count": 3,
    },
    {
      "cause": "Cảm biến xylanh không hoạt động",
      "error_id": 28,
      "error_name": "Bất thường xylanh/Cylinder error",
      "solution": "Kiểm tra cảm biến hoặc từ trong xylanh...",
      "used_count": 2,
    },
  ],
};

dynamic getListConfirm_example = {
  "data": [
    {
      "error_code": "G0014",
      "error_name": "Gắp lỗi/Picking error",
      "error_type": "Gắp lỗi/Picking error",
      "id": 318,
      "line": "GEN3",
      "location": "11",
      "machine_name": "Gap VI Automatically visual inspecttion Gap",
      "machine_type": "XY Machine",
      "runtime_min": 4586,
      "start_time": "2025-07-15 08:44:11",
      "status": "ERROR",
    },
    {
      "error_code": "G0015",
      "error_name": "Rơi liệu/ Material drop",
      "error_type": "Rơi liệu/ Material drop",
      "id": 314,
      "line": "GEN3",
      "location": "11",
      "machine_name": "Gap VI Automatically visual inspecttion Gap",
      "machine_type": "XY Machine",
      "runtime_min": 4466,
      "start_time": "2025-07-15 10:44:13",
      "status": "ERROR",
    },
    {
      "error_code": "G0015",
      "error_name": "Rơi liệu/ Material drop",
      "error_type": "Rơi liệu/ Material drop",
      "id": 319,
      "line": "GEN3",
      "location": "11",
      "machine_name": "Gap VI Automatically visual inspecttion Gap",
      "machine_type": "XY Machine",
      "runtime_min": 4344,
      "start_time": "2025-07-15 12:46:13",
      "status": "ERROR",
    },
  ],
};
dynamic getErrorByCode_example = {
  "error_list": [
    {
      "cause": "Xylanh không đi hết hành trình",
      "error_code": "G0012",
      "error_name": "Bất thường xylanh/Cylinder error",
      "id": 27,
      "solution": "Kiểm tra van, khí, đế van...",
    },
    {
      "cause": "Cảm biến xylanh không hoạt động",
      "error_code": "G0012",
      "error_name": "Bất thường xylanh/Cylinder error",
      "id": 28,
      "solution": "Kiểm tra cảm biến hoặc từ trong xylanh...",
    },
  ],
  "idconfirm": 14,
};
dynamic getViewMaintenance_monthly_example = {
  "history": [
    {
      "action_taken": "Thay dầu và lọc dầu",
      "content": "Kiểm tra dầu thủy lực",
      "created_at": "2025-07-26 11:47:53.140000",
      "maintainer": "Nguyễn Đức Hải",
      "maintenance_type": "MONTHLY",
      "no": 1,
      "tech_spec": "Dầu thủy lực không đục, nhiệt độ ổn định",
    },
    {
      "action_taken": "Thay dầu và lọc dầu",
      "content": "Kiểm tra dầu thủy lực",
      "created_at": "2025-07-26 11:09:17.427000",
      "maintainer": "Nguyễn Đức Hải",
      "maintenance_type": "MONTHLY",
      "no": 2,
      "tech_spec": "Dầu thủy lực không đục, nhiệt độ ổn định",
    },
  ],
  "machine_info": {
    "machine_name": "Gap VI Automatically visual inspecttion Gap",
  },
};
dynamic getViewMaintenance_weekly_example = {
  "history": [
    {
      "action_taken": "Thay đầu mạng",
      "content": "Kiểm tra PLC",
      "created_at": "2025-07-26 12:17:39.483000",
      "maintainer": "Nguyễn Đức Hải",
      "maintenance_type": "WEEKLY",
      "no": 1,
      "tech_spec": "Dây mạng oke, đầu mạng sắp hỏng ",
    },
  ],
  "machine_info": {
    "machine_name": "Gap VI Automatically visual inspecttion Gap",
  },
};

dynamic apiMachineMachineStatus = [
  {
    "LINE": "Line_1F",
    "PRINTER": "NA-None",
    "H1": "RUN-None",
    "H2": "RUN-None",
    "H3": "RUN-None",
    "H4": "RUN-None",
    "H5": "RUN-None",
    "H6": "RUN-None",
    "H7": "RUN-None",
    "H8": "RUN-None",
    "REFLOW": "RUN-None",
  },
  {
    "LINE": "Line_1R",
    "PRINTER": "NA-None",
    "H1": "RUN-None",
    "H2": "RUN-None",
    "H3": "RUN-None",
    "H4": "RUN-None",
    "H5": "RUN-None",
    "H6": "RUN-None",
    "H7": "RUN-None",
    "H8": "RUN-None",
    "REFLOW": null,
  },
  {
    "LINE": "Line_2F",
    "PRINTER": "NA-None",
    "H1": "RUN-None",
    "H2": "RUN-None",
    "H3": "RUN-None",
    "H4": "RUN-None",
    "H5": "RUN-None",
    "H6": "RUN-None",
    "H7": "RUN-None",
    "H8": "RUN-None",
    "REFLOW": "RUN-None",
  },
  {
    "LINE": "Line_2R",
    "PRINTER": "NA-None",
    "H1": "RUN-None",
    "H2": "RUN-None",
    "H3": "RUN-None",
    "H4": "RUN-None",
    "H5": "RUN-None",
    "H6": "RUN-None",
    "H7": "RUN-None",
    "H8": "RUN-None",
    "REFLOW": null,
  },
  {
    "LINE": "Line_4F",
    "PRINTER": "OFFt-None",
    "H1": "RUN-None",
    "H2": "RUN-None",
    "H3": "RUN-None",
    "H4": "RUN-None",
    "H5": "RUN-None",
    "H6": "RUN-None",
    "H7": "RUN-None",
    "H8": "RUN-None",
    "REFLOW": "RUN-None",
  },
  {
    "LINE": "Line_4R",
    "PRINTER": "NA-None",
    "H1": "RUN-None",
    "H2": "RUN-None",
    "H3": "RUN-None",
    "H4": "RUN-None",
    "H5": "RUN-None",
    "H6": "RUN-None",
    "H7": "RUN-None",
    "H8": "RUN-None",
    "REFLOW": null,
  },
  {
    "LINE": "Line_5F",
    "PRINTER": "NA-None",
    "H1": "RUN-None",
    "H2": "RUN-None",
    "H3": "RUN-None",
    "H4": "ERROR-180343",
    "H5": "RUN-None",
    "H6": null,
    "H7": "RUN-None",
    "H8": "RUN-None",
    "REFLOW": "RUN-None",
  },
  {
    "LINE": "Line_5R",
    "PRINTER": "RUN-None",
    "H1": "RUN-None",
    "H2": "RUN-None",
    "H3": "RUN-None",
    "H4": "ERROR-180343",
    "H5": "RUN-None",
    "H6": null,
    "H7": "RUN-None",
    "H8": "RUN-None",
    "REFLOW": null,
  },
];
